
package com.example.demo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "customerWebService", targetNamespace = "http://service.dlyx.ccie.com", wsdlLocation = "http://localhost:9992/api/webservice/customer?wsdl")
public class CustomerWebService_Service
    extends Service
{

    private final static URL CUSTOMERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERWEBSERVICE_EXCEPTION;
    private final static QName CUSTOMERWEBSERVICE_QNAME = new QName("http://service.dlyx.ccie.com", "customerWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9992/api/webservice/customer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERWEBSERVICE_WSDL_LOCATION = url;
        CUSTOMERWEBSERVICE_EXCEPTION = e;
    }

    public CustomerWebService_Service() {
        super(__getWsdlLocation(), CUSTOMERWEBSERVICE_QNAME);
    }

    public CustomerWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERWEBSERVICE_QNAME, features);
    }

    public CustomerWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERWEBSERVICE_QNAME);
    }

    public CustomerWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERWEBSERVICE_QNAME, features);
    }

    public CustomerWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerWebService
     */
    @WebEndpoint(name = "CustomerWebServiceImplPort")
    public CustomerWebService getCustomerWebServiceImplPort() {
        return super.getPort(new QName("http://service.dlyx.ccie.com", "CustomerWebServiceImplPort"), CustomerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWebService
     */
    @WebEndpoint(name = "CustomerWebServiceImplPort")
    public CustomerWebService getCustomerWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.dlyx.ccie.com", "CustomerWebServiceImplPort"), CustomerWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERWEBSERVICE_EXCEPTION!= null) {
            throw CUSTOMERWEBSERVICE_EXCEPTION;
        }
        return CUSTOMERWEBSERVICE_WSDL_LOCATION;
    }

}
