
package com.example.demo.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "customerWebService", targetNamespace = "http://service.dlyx.ccie.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.demo.webservice.ObjectRestResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.InsertResponse")
    public ObjectRestResponse insert(
        @WebParam(name = "arg0", targetNamespace = "")
        CustomerReqVo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.demo.webservice.ObjectRestResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertCrew", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.InsertCrew")
    @ResponseWrapper(localName = "insertCrewResponse", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.InsertCrewResponse")
    public ObjectRestResponse insertCrew(
        @WebParam(name = "arg0", targetNamespace = "")
        TCrewReqVo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.demo.webservice.ObjectRestResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertHighSeas", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.InsertHighSeas")
    @ResponseWrapper(localName = "insertHighSeasResponse", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.InsertHighSeasResponse")
    public ObjectRestResponse insertHighSeas(
        @WebParam(name = "arg0", targetNamespace = "")
        HighSeasReqVo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.demo.webservice.ObjectRestResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteHighSeas", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.DeleteHighSeas")
    @ResponseWrapper(localName = "deleteHighSeasResponse", targetNamespace = "http://service.dlyx.ccie.com", className = "com.example.demo.webservice.DeleteHighSeasResponse")
    public ObjectRestResponse deleteHighSeas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
