
package com.example.demo.webservicelocal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "contractWebService", targetNamespace = "http://contract.mdm.com", wsdlLocation = "http://10.126.15.230:9220/gapi/webservice/contract?wsdl")
public class ContractWebService_Service
    extends Service
{

    private final static URL CONTRACTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTRACTWEBSERVICE_EXCEPTION;
    private final static QName CONTRACTWEBSERVICE_QNAME = new QName("http://contract.mdm.com", "contractWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.126.15.230:9220/gapi/webservice/contract?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTRACTWEBSERVICE_WSDL_LOCATION = url;
        CONTRACTWEBSERVICE_EXCEPTION = e;
    }

    public ContractWebService_Service() {
        super(__getWsdlLocation(), CONTRACTWEBSERVICE_QNAME);
    }

    public ContractWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTRACTWEBSERVICE_QNAME, features);
    }

    public ContractWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTRACTWEBSERVICE_QNAME);
    }

    public ContractWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTRACTWEBSERVICE_QNAME, features);
    }

    public ContractWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContractWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContractWebService
     */
    @WebEndpoint(name = "ContractWebServiceImplPort")
    public ContractWebService getContractWebServiceImplPort() {
        return super.getPort(new QName("http://contract.mdm.com", "ContractWebServiceImplPort"), ContractWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContractWebService
     */
    @WebEndpoint(name = "ContractWebServiceImplPort")
    public ContractWebService getContractWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://contract.mdm.com", "ContractWebServiceImplPort"), ContractWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTRACTWEBSERVICE_EXCEPTION!= null) {
            throw CONTRACTWEBSERVICE_EXCEPTION;
        }
        return CONTRACTWEBSERVICE_WSDL_LOCATION;
    }

}
