
package com.example.demo.webservicelocal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "netHallContractWebService", targetNamespace = "http://netHallContract.mdm.com", wsdlLocation = "http://10.129.60.185:9992/api/webservice/netHallContract?wsdl")
public class NetHallContractWebService_Service
    extends Service
{

    private final static URL NETHALLCONTRACTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException NETHALLCONTRACTWEBSERVICE_EXCEPTION;
    private final static QName NETHALLCONTRACTWEBSERVICE_QNAME = new QName("http://netHallContract.mdm.com", "netHallContractWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.129.60.185:9992/api/webservice/netHallContract?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETHALLCONTRACTWEBSERVICE_WSDL_LOCATION = url;
        NETHALLCONTRACTWEBSERVICE_EXCEPTION = e;
    }

    public NetHallContractWebService_Service() {
        super(__getWsdlLocation(), NETHALLCONTRACTWEBSERVICE_QNAME);
    }

    public NetHallContractWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NETHALLCONTRACTWEBSERVICE_QNAME, features);
    }

    public NetHallContractWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, NETHALLCONTRACTWEBSERVICE_QNAME);
    }

    public NetHallContractWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NETHALLCONTRACTWEBSERVICE_QNAME, features);
    }

    public NetHallContractWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetHallContractWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NetHallContractWebService
     */
    @WebEndpoint(name = "NetHallContractWebServiceImplPort")
    public NetHallContractWebService getNetHallContractWebServiceImplPort() {
        return super.getPort(new QName("http://netHallContract.mdm.com", "NetHallContractWebServiceImplPort"), NetHallContractWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetHallContractWebService
     */
    @WebEndpoint(name = "NetHallContractWebServiceImplPort")
    public NetHallContractWebService getNetHallContractWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://netHallContract.mdm.com", "NetHallContractWebServiceImplPort"), NetHallContractWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETHALLCONTRACTWEBSERVICE_EXCEPTION!= null) {
            throw NETHALLCONTRACTWEBSERVICE_EXCEPTION;
        }
        return NETHALLCONTRACTWEBSERVICE_WSDL_LOCATION;
    }

}
