
package com.example.demo.net;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NetContractServiceImplService", targetNamespace = "http://impl.netcontractService.service.marketing.clickpaas.com/", wsdlLocation = "http://crm-test.lab.chnenergy.com.cn/marketingapi/service//netContractService?wsdl")
public class NetContractServiceImplService
    extends Service
{

    private final static URL NETCONTRACTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NETCONTRACTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName NETCONTRACTSERVICEIMPLSERVICE_QNAME = new QName("http://impl.netcontractService.service.marketing.clickpaas.com/", "NetContractServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://crm-test.lab.chnenergy.com.cn/marketingapi/service//netContractService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETCONTRACTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        NETCONTRACTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public NetContractServiceImplService() {
        super(__getWsdlLocation(), NETCONTRACTSERVICEIMPLSERVICE_QNAME);
    }

    public NetContractServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NETCONTRACTSERVICEIMPLSERVICE_QNAME, features);
    }

    public NetContractServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, NETCONTRACTSERVICEIMPLSERVICE_QNAME);
    }

    public NetContractServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NETCONTRACTSERVICEIMPLSERVICE_QNAME, features);
    }

    public NetContractServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetContractServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NetContractService
     */
    @WebEndpoint(name = "NetContractServiceImplPort")
    public NetContractService getNetContractServiceImplPort() {
        return super.getPort(new QName("http://impl.netcontractService.service.marketing.clickpaas.com/", "NetContractServiceImplPort"), NetContractService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetContractService
     */
    @WebEndpoint(name = "NetContractServiceImplPort")
    public NetContractService getNetContractServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.netcontractService.service.marketing.clickpaas.com/", "NetContractServiceImplPort"), NetContractService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETCONTRACTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw NETCONTRACTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return NETCONTRACTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
