
package com.example.demo.net;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetContractService", targetNamespace = "http://netcontractService.service.marketing.clickpaas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NetContractService {


    /**
     * 
     * @param netContractParam
     * @return
     *     returns com.example.demo.net.NetContractRespParam
     */
    @WebMethod(action = "netContractSaveOrUpdate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "netContractSaveOrUpdate", targetNamespace = "http://netcontractService.service.marketing.clickpaas.com/", className = "com.example.demo.net.NetContractSaveOrUpdate")
    @ResponseWrapper(localName = "netContractSaveOrUpdateResponse", targetNamespace = "http://netcontractService.service.marketing.clickpaas.com/", className = "com.example.demo.net.NetContractSaveOrUpdateResponse")
    public NetContractRespParam netContractSaveOrUpdate(
        @WebParam(name = "netContractParam", targetNamespace = "")
        NetContractParam netContractParam);

    /**
     * 
     * @param id
     * @return
     *     returns com.example.demo.net.NetContractRespParam
     */
    @WebMethod(action = "querySaleRemainEleInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "querySaleRemainEleInfo", targetNamespace = "http://netcontractService.service.marketing.clickpaas.com/", className = "com.example.demo.net.QuerySaleRemainEleInfo")
    @ResponseWrapper(localName = "querySaleRemainEleInfoResponse", targetNamespace = "http://netcontractService.service.marketing.clickpaas.com/", className = "com.example.demo.net.QuerySaleRemainEleInfoResponse")
    public NetContractRespParam querySaleRemainEleInfo(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
